### ISSUE TITLE
It’s just a AboutMe page so make the changes accordingly.

### ISSUE THREAD

**Issue by codingiitg** [Coding-Club-IITG/Codepeak-beginner-HTML-task#1]
It’s just an AboutMe page so make the changes accordingly.

**Comment by atishay1743** [comment]
I want to solve this issue

**Comment by codingiitg** [comment]
> I want to solve this issue

Yes okay

**Comment by dahiya-code** [comment]
Can I solve this issue ?
Name : Navya Dahiya

**Comment by codingiitg** [comment]
> Can I solve this issue ?
> Name : Navya Dahiya

yes, go ahead..

**Comment by pranav-agarwal800** [comment]
Can I solve this issue?
Pranav Agarwal

**Comment by codingiitg** [comment]
> Can I solve this issue?
> Pranav Agarwal

yes

**Comment by Soumadipdas18** [comment]
I want to solve it
name- Soumadip Das

**Comment by codingiitg** [comment]
> I want to solve it
> name- Soumadip Das

yes

**Comment by TESLA2402** [comment]
can I solve this issue?
Name : Lakshay

**Comment by codingiitg** [comment]
> can I solve this issue?
> Name : Lakshay

yes

**Comment by C-Omkar** [comment]
Can I solve this issue
Name: Omkar

**Comment by codingiitg** [comment]
> Can I solve this issue
> Name: Omkar

go ahead

**Comment by KuraPriyanka** [comment]
Can I solve this issue?
Name: Priyanka

**Comment by codingiitg** [comment]
> Can I solve this issue?
> Name: Priyanka

yes go ahead

**Comment by nigkhar23** [comment]
Can I solve this issue?
Name: Prakhar

**Comment by codingiitg** [comment]
> Can I solve this issue?
> Name: Prakhar

yes

**Comment by rajkishore1121** [comment]
Can I solve the issue?
Name: Raj Kishore

**Comment by codingiitg** [comment]
> Can I solve the issue?
> Name: Raj Kishore

yes

**Comment by Raeskaa** [comment]
Can I solve the issue?
Name: Mahesh Tripathi

**Comment by shrishtickling** [comment]
Can I solve the issue?
Name: Shrishti Singh

**Comment by codingiitg** [comment]
> Can I solve the issue?
> Name: Mahesh Tripathi

go ahead

**Comment by codingiitg** [comment]
> Can I solve the issue?
> Name: Shrishti Singh

yes

**Comment by dhaneshragu** [comment]
Can I solve this issue?

**Comment by Rishikant24** [comment]
How do i contribute to this issue?

**Comment by codingiitg** [comment]
> How do i contribute to this issue?

Hi , go through the issue and the codebase and try to rectify/find the error and then try to solve it. If you are solving this then reply to this , and I will assign it to you!

**Comment by Rishikant24** [comment]
yes, i would like to solve this, please assign it to me

**Comment by 1ananya3** [comment]
Hi,Can I solve this issue?

**Comment by 1ananya3** [comment]
There is a spelling mistake "Interensts".It will be "Interests". Can I make a new issue to change this ?

**Comment by codingiitg** [comment]
@Rishikant24 @1ananya3 , You both can work on the issue . All the best

**Comment by Rishikant24** [comment]
I have pulled a request to merge my commit on the "About Me" issue. 
Please look into it, and when will I be awarded the points?

**Comment by Sunidhi-Tiwari** [comment]
can I work on this issue?

**Comment by mikrokosmos2109** [comment]
Can I do this task?
Keerti Lata

**Comment by re4lvanshsingh** [comment]
Could i contribute as well? Please assign me this task

**Comment by chiranjibismg** [comment]
can i contribute to this this project ?

**Comment by Jagadeesh17402** [comment]
@codingiitg could you please assign me this issue ?

**Comment by adv6273** [comment]
can i solve this issue?
