### ISSUE TITLE
Animated Background

### ISSUE THREAD

**Issue by AmreshSinha** [Coding-Club-IITG/Codepeak-beginner-HTML-task#15]
You can also try adding Animated Background (like continuous changing gradient).
To make it less cumbersome
1st. Make another branch named 'animated'
2nd. Remove the day-night switcher button and CSS for that.
3rd. Remove the js at the end of the page which was switching the theme.
 
Then, implement your Animated Background in CSS, SCSS, JS, or in whatever method you prefer.

*This issue will give you more insights in branching and html background animation.

**Comment by shrishtickling** [comment]
Can I solve this issue ?
Name : Shrishti Singh

**Comment by Raeskaa** [comment]
Can I solve this issue ?
Name : Mahesh Tripathi

**Comment by codingiitg** [comment]
yes @shrishtickling @Raeskaa

**Comment by Soumadipdas18** [comment]
amssign it to me
i can solve

**Comment by codingiitg** [comment]
> amssign it to me
> i can solve

yes

**Comment by aritroCoder** [comment]
I have added the animations. Please assign this to me

https://user-images.githubusercontent.com/92646038/144715613-b6dfcd25-da81-48e8-bc99-f3307ed3a507.mp4

**Comment by codingiitg** [comment]
> I have added the animations. Please assign this to me
> 
>  2021-12-04.21-12-55.mp4

👍

**Comment by aritroCoder** [comment]
I have started a PR. Please merge it

**Comment by codingiitg** [comment]
> I have started a PR at #28 . Please merge it

as it is beginners project , we wont be merging the PRs but we will accept the PR . So you will get the points

**Comment by Rishikant24** [comment]
can I solve this issue?

**Comment by pradeepgovind12** [comment]
can i solve this ?

**Comment by Gayathri-Elan** [comment]
can I solve this issue?

**Comment by re4lvanshsingh** [comment]
@codingiitg could u assign me the issue? thankyou

**Comment by Jagadeesh17402** [comment]
@codingiitg  could u assign this issue  to me ?

**Comment by adv6273** [comment]
can i solve this?
