### ISSUE TITLE
Redirect function not working

### ISSUE THREAD

**Issue by codingiitg** [Coding-Club-IITG/Codepeak-beginner-HTML-task#3]
In the bottom of the webpage some buttons are redirecting to the same about me page ,make them to redirect to example.com

**Comment by atishay1743** [comment]
i want to solve

**Comment by codingiitg** [comment]
> i want to solve

okay you can

**Comment by Kunalpal215** [comment]
Can I solve this issue ?
Name : Kunal Pal

**Comment by codingiitg** [comment]
> Can I solve this issue ?
> Name : Kunal Pal

yes you can!

**Comment by ratansen** [comment]
Can I solve this issue?
Name :  Ratan Sen

**Comment by dahiya-code** [comment]
Can I solve this issue ?
Name : Navya Dahiya

**Comment by codingiitg** [comment]
Yes @ratansen @dahiya-code

**Comment by pranav-agarwal800** [comment]
Can i solve this issue?
Pranav Agarwal

**Comment by codingiitg** [comment]
> Can i solve this issue?
> Pranav Agarwal

yes

**Comment by Soumadipdas18** [comment]
I want to solve it
name- Soumadip Das

**Comment by codingiitg** [comment]
> I want to solve it
> name- Soumadip Das

yes

**Comment by TESLA2402** [comment]
Can I solve this Issue ?
Name : Lakshay

**Comment by codingiitg** [comment]
> Can I solve this Issue ?
> Name : Lakshay

yes

**Comment by C-Omkar** [comment]
Can I solve this issue?
Name: Omkar

**Comment by codingiitg** [comment]
> Can I solve this issue?
> Name: Omkar

yes

**Comment by KuraPriyanka** [comment]
Can I solve this issue?
Name: Priyanka

**Comment by codingiitg** [comment]
> Can I solve this issue?
> Name: Priyanka

yes go ahead

**Comment by nigkhar23** [comment]
Can I solve this issue?
Name: Prakhar

**Comment by codingiitg** [comment]
> Can I solve this issue?
> Name: Prakhar

yes

**Comment by shrishtickling** [comment]
Can I solve this issue?
Name: Shrishti Singh

**Comment by Raeskaa** [comment]
Can I solve this issue?
Name: Mahesh Tripathi

**Comment by codingiitg** [comment]
Yes @shrishtickling  @Raeskaa

**Comment by letsintegreat** [comment]
I'd like to work on this.

**Comment by Rishikant24** [comment]
I would like to solve this issue

**Comment by Rishikant24** [comment]
I had already committed and sent my PR for #3 yesterday (7/12/21) itself. Now should I redo it or will that PR be accepted??

**Comment by Ananmayd** [comment]
i want to solve the issue

**Comment by mikrokosmos2109** [comment]
I want to solve this issue, can you assign it to me.

**Comment by chiranjibismg** [comment]
Can i solve this issue

**Comment by Gayathri-Elan** [comment]
Can i solve this issue?

**Comment by re4lvanshsingh** [comment]
@codingiitg could u assign me the issue? thankyou

**Comment by Jagadeesh17402** [comment]
@codingiitg   could  you  assign me this issue ?

**Comment by adv6273** [comment]
can i solve this?
@codingiitg
